### ISSUE TITLE
Example gives 13 errors in Swift 4 in Xcode 10+

### ISSUE THREAD

**Issue by itadreik4** [intuit/CardParts#101]
When I open the example project and build it, I get 13 errors. I am using Swift 4.2.1 in XCode 10.1. All I did was load up the example project and "pod install" with the terminal. It installed 6 pods, then I rebuilt the project. Build fails with 13 errors.

**Comment by OlionCompany** [comment]
@itadreik4 I have, same errors...
How I resolved problems:
Go to "Pods" -> Build Settings -> Search SWIFT_VERSION -> setup Swift 4.0 for all targets with Swift 3.0.

**Comment by lwdupont** [comment]
Ya, we'll see if we can get a Swift 4.2 release out this week sometime.

**Comment by lwdupont** [comment]
I just released this to cocoapods.
