### ISSUE TITLE
XCode 10 Example not compiling 

### ISSUE THREAD

**Issue by PrashantKT** [intuit/CardParts#105]
I have downloaded zip file then in Example folder  i have fired pod install. 

Still getting following error 

 /Users/prashant/Downloads/CardParts-master/Example/Pods/Pods/Target Support Files/Pods-CardParts_Example/Pods-CardParts_Example.debug.xcconfig: unable to open file (in target "CardParts_Example" in project "CardParts") (in target 'CardParts_Example')

and 

 /Users/prashant/Downloads/CardParts-master/Example/Pods/Pods/Target Support Files/Pods-CardParts_Tests/Pods-CardParts_Tests.debug.xcconfig: unable to open file (in target "CardParts_Tests" in project "CardParts") (in target 'CardParts_Tests')

Please suggest

**Comment by PrashantKT** [comment]
Okay so gem install cocoapods --pre fixes the issue If any one has same issue .

**Comment by lwdupont** [comment]
Ya, it was a decision by the team to need to run that in order to run the example. Sounds like we could improve the docs. Do a pull request? :)
