### ISSUE TITLE
Help Wanted: Having Issue Building Examples

### ISSUE THREAD

**Issue by ppbpdx** [intuit/CardParts#106]
Hi I was wondering if you can point me in the right direction. I downloaded the project and in the /examples directory ran 'pod install' it seemed to install the necessary pods, however, when I try to build the project I get a number of errors including on the MainViewController it says it cannot find CardParts to import.

Should I run the pod install at a different level and not in the examples directory. Any help for the fastest path to being able to check out the examples is greatly appreciated. This looks like a really cool library and I am looking forward to using it.

Xcode Version 10.1 (10B61)

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8325532a439a86921f03327ab078b5e1acea6790
```
### Installation Source
```
Executable Path: /usr/local/bin/pod
```
### Plugins
```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0

**Comment by lwdupont** [comment]
It's been a while since I've tried the instructions, but I don't think they've changed. 

Try this line, should work? https://github.com/intuit/CardParts#example

**Comment by CarioniStefano** [comment]
Same here, downloaded the example, run 'pod install' but there is no way to get it run.
I get these errors
![image](https://user-images.githubusercontent.com/12976725/50249958-d05f2f00-03df-11e9-9e23-17625882bdbd.png)

**Comment by lwdupont** [comment]
Hmm.. @croossin @bharathmurs any ideas?

**Comment by CarioniStefano** [comment]
'gem install cocoapods --pre'

running this before 'pod install' fix the issues, I think you need to add it to the readme 👍
