### ISSUE TITLE
Help Wanted: Spacing on CardPartPagedView

### ISSUE THREAD

**Issue by ppbpdx** [intuit/CardParts#108]
I am trying to get the paged cards (CardPartPagedView) to fill the sides of the screen without a white space. On the other cards I can use the margins and set them to 0 and that seems to work, however, I cannot figure out how to do it in the CardPartPagedView.

Any pointers greatly appreciated.

![space](https://user-images.githubusercontent.com/5177162/51091394-07a2d080-173f-11e9-924f-423f823b7f16.png)

**Comment by barcister** [comment]
You need to modify this value in order to change that: CardParts.theme.cardPartMargins

**Comment by croossin** [comment]
@ppbpdx You can update margins and spacing via the theme 😄
