### ISSUE TITLE
How do I get `cardClicked` callback?

### ISSUE THREAD

**Issue by sasquatchgit** [intuit/CardParts#110]

**Comment by k3street** [comment]
I wasn’t trying to be a jerk, the base class has a cardtapped function that is accessible when you instantiate the class and a long press tap gesture recognizer.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sasquatchgit** [comment]
Hey @k3street , sorry if it came that way. I was trying to say that I am noob, and even after reading the readme, I wasn't able to figure how to use it. I would be really thankful if someone could put an example on how to achieve it. And thanks for taking your time and trying to help me.

**Comment by sasquatchgit** [comment]
Should I override the function to use it?

**Comment by croossin** [comment]
Thank you @k3street for trying to explain, much appreciated!

@sasquatchgit If you take a look at [Clickable Cards documentation](https://github.com/intuit/CardParts#clickable-cards) you can see how we achieve that! So in your CardViewController you just simply need to add:
```swift
self.cardTapped(forState: .empty) {
    print("Card was tapped in .empty state!")
}

self.cardTapped(forState: .hasData) {
    print("Card was tapped in .hasData state!")
}

// The default state for setupCardParts([]) is .none
self.cardTapped {
    print("Card was tapped in .none state")
}
```

and then those handlers will be called!  Please feel free to reopen if that does not answer your question.
