### ISSUE TITLE
Use of unresolved identifier Variable("")

### ISSUE THREAD

**Issue by thunpisit** [intuit/CardParts#117]
I'm new to CardParts and I'm playing with it to implement it to my app. For some reason, my Xcode does not recognize Variable("") and yelling Use of unresolved identifier Variable("")
    
    var title = Variable("")
    var text = Variable("")
    
    init() {
        
        // When these values change, the UI in the TestCardController
        // will automatically update
        title.value = "Hello, world!"
        text.value = "CardParts is awesome!"
    }

**Comment by thunpisit** [comment]
#helpwatnted

**Comment by lwdupont** [comment]
You might be missing doing:

import RxSwift
import RxCocoa

CardParts includes that as a dependency in the Cocoapods spec, but you do need to include it if you are going to use it in a (what looks like) a subclass.

**Comment by thunpisit** [comment]
@lwdupont Thank you so much, that eliminate the problem with variable but now I am facing another problem which yelling: Value of type 'CardPartTextView' has no member 'reactive' on each of these both lines.

        viewModel.title.asObservable().bind(to: titlePart.reactive.title).disposed(by: bag)
        viewModel.text.asObservable().bind(to: textPart.reactive.text).disposed(by: bag)

**Comment by croossin** [comment]
@thunpisit Whoops! It seems that the README has some old code in it... Instead of `titlePart.reactive.title` it should be `titlePart.rx.title`! Thanks for that catch and I will go ahead and update the README.

**Comment by croossin** [comment]
Have merged PR #121 - thanks again for the catch @thunpisit !

**Comment by croossin** [comment]
Fixed by version [2.7.5](https://github.com/intuit/CardParts/releases/tag/2.7.5).
