### ISSUE TITLE
Still having issues with layout constraints after #100 closed. 

### ISSUE THREAD

**Issue by jem5519** [intuit/CardParts#118]
Pulled down version 2.7.4. 

layout constraints still seem to be showing up. But, now the app appears to be be trying to invalidate the layout and retrying. Note in the video that the error messages continue to appear in the console event the ought the app appears to be idle.

https://www.dropbox.com/s/tc588wc2wtt14dx/CardParts.mp4?dl=0

**Comment by bharathmurs** [comment]
Hi @jem5519,
We have taken care of the issue with this PR https://github.com/intuit/CardParts/pull/119.

**Comment by jem5519** [comment]
In fairness, can we refrain from “closing” an issue until the person who opened it gets a chance to TEST it?

**Comment by croossin** [comment]
Sure, @jem5519, we can do that.

**Comment by jem5519** [comment]
Thanks.

Where can I pull down a copy of the fixed source?


- Jim

**Comment by bharathmurs** [comment]
@jem5519 If you are check the branch `bug/fix_autolayout` until we merge and do a release.

**Comment by jem5519** [comment]
Thank you for all your efforts, bharathmurs! I did pull it down and the console is clean! Please close this issue.

**Comment by croossin** [comment]
Closing this issue as fixed by version [2.7.5](https://github.com/intuit/CardParts/releases/tag/2.7.5).
