### ISSUE TITLE
use navigation navigation controller

### ISSUE THREAD

**Issue by WingCH** [intuit/CardParts#126]
![IMG_2065](https://user-images.githubusercontent.com/19588517/54121588-d4767800-4435-11e9-8cb4-1c88ada2f20c.jpg)

How to make the card view and bar has a spacing?

**Comment by WingCH** [comment]
i have find the solution
`self.collectionView.contentInset.top = 5`

**Comment by croossin** [comment]
Great! Let us know if there is anything else you need help with.
