### ISSUE TITLE
[help wanted] Problem with Layouts

### ISSUE THREAD

**Issue by Slethael** [intuit/CardParts#128]
Hi everyone !

I am currently building a custom app for my little sister to help her get better at mental calculation, but I'm stuck at the very early stages..

I want it to be a bit appealing, and I find the design of the Mint application beautiful, so I want to re-create something like this.

I tried several things but the image I add still resize, independently of the constraints I add.

Basically, my image is 64 by 64, .png format, but it resizes to take the whole thing.

How it looks : [zoomed image](https://imgur.com/a/sbKjNUt)

Here is my code : 
`         super.viewDidLoad()
        
        view.addConstraint(NSLayoutConstraint(item: view, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1, constant: 400)) // The card should take all the screen, but it's just to get a grasp of how it works for now
        
        /* Creating the title of the card */
        let textPart = CardPartTextView(type: .header)
        textPart.text = "Calcul mental"
        textPart.textAlignment = .center
        textPart.textColor = .white
        /* End of creation of the title */
        
        /* Creating the image part */
        let imagePart = CardPartImageView()
        imagePart.image = UIImage(named: "Brain")
        /* End of creation of the image */
        
        view.addSubview(imagePart)
        
        // My problem starts here. I tried several things but none of them works, see the logs for more information
        // The first constraint ("test" variable) is the one giving me problems, the last seems to work fine
        imagePart.translatesAutoresizingMaskIntoConstraints = false

        let test = NSLayoutConstraint.constraints(withVisualFormat: "H:|-(155@1000)-[imgPart(64@1000)]-(156@1000)-|", metrics: nil, views: ["imgPart": imagePart])
        NSLayoutConstraint.activate(test)

        imagePart.addConstraint(NSLayoutConstraint(item: imagePart, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1, constant: 250))
        setupCardParts([imagePart, textPart])
    
`

And here's the logs : [Pastebin Logs](https://pastebin.com/U3FWiU5T)
(Sorry for that, GitHub code tags wouldn't let me format my logs, as well as for the code above but it's a bit more acceptable)

The thing is I'm not very comfortable with Swift development.
As said in the comments of the code, I tried several different things but none of them works and I'm lost now.

Seems like CardPartImageView adds constraints (padding of 28) but when I try to print them, they don't show up.

I also took a look a several tutorials concerning VFL and laying out in Swift but still ...

Thank you in advance, and also great work with this lib, it looks gorgeous !

**Comment by bharathmurs** [comment]
@Slethael,
I see issues in laying out the constraints with test and imagePart is adding a constraint of 250.

You might want to try getting rid of all those constraints and add these
```
imagePart.translatesAutoresizingMaskIntoConstraints = false 
imagePart..heightAnchor.constraint(equalToConstant: 64.0).isActive = true
```

**Comment by Slethael** [comment]
Hello @bharathmurs,

I tried what you told me to do. Seems like the height of the picture is now set but the width is still resized, like so : [width resized](https://imgur.com/a/CrxTIp8)

I got rid of all of the constraints, except the one setting the height of the superview.

Thanks for your help :)

**Comment by bharathmurs** [comment]
You might want to set 
imagePart.contentMode = .scaleAspectFit

**Comment by Slethael** [comment]
Yay, that was it !

I see that this is a vanilla Swift enum, I seriously lack some basics Swift development ...

Thank you for your help !

**Comment by bharathmurs** [comment]
Gret. Thanks @Slethael. I will be closing the issue then.
