### ISSUE TITLE
Swift 5 and Xcode 10.2 support?

### ISSUE THREAD

**Issue by scjc** [intuit/CardParts#130]
When can we expect support for swift 5?

**Comment by lwdupont** [comment]
I'll take a crack at it this weekend @croossin @bharathmurs if that's cool with you. (I'm on call for work so will be at work Saturday morning, sounds like a fun project :))

**Comment by croossin** [comment]
@scjc Feel free to take a look at the PR @lwdupont opened up - #132.

**Comment by scjc** [comment]
@croossin @lwdupont thanks for the update!

**Comment by lwdupont** [comment]
Published to Cocoapods:

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  CardParts (2.8.0) successfully published
 📅  April 14th, 12:21
 🌎  https://cocoapods.org/pods/CardParts
 👍  Tell your friends!
--------------------------------------------------------------------------------
