### ISSUE TITLE
Change background color [Help Wanted]

### ISSUE THREAD

**Issue by vicxruiz** [intuit/CardParts#131]
How can i change the background color from gray to white?

**Comment by croossin** [comment]
Hi @vicxruiz - which background color are you referring to? The cards background color? The collection views background color?

**Comment by vicxruiz** [comment]
@croossin the collection view

**Comment by croossin** [comment]
You can simply change the collectionView background color in your `CardsViewController` by doing the following: `self.collectionView.backgroundColor = .purple`.

Let me know if this does not satisfy your question!
