### ISSUE TITLE
Change background colour of View Controller

### ISSUE THREAD

**Issue by scjc** [intuit/CardParts#138]
So have a normal view controller which loads up with `loadCards(cards: cards)`(similar to the example's `MainViewController.swift`)

 I would like to change the background colour. I have tried changing it in storyboards and also using `self.view.backgroundColor = UIColor(red:0.21, green:0.21, blue:0.21, alpha:1.0)` in the `viewDidLoad()`

However, neither has worked and I'm not really sure how else to set the background view

Any help is much appreciated and many thanks in advance!

**Comment by croossin** [comment]
If you take a look at issue #131 you will be able to understand how to change the background color.  Let me know if that does not solve your issue.

**Comment by scjc** [comment]
I believe that is more targeted towards the card it self, I meant the entire view's background colour which hold all the cards (CardsViewController)
