### ISSUE TITLE
CardPartTableView doesn't have a top margin, even when manually set

### ISSUE THREAD

**Issue by hoidofyolen** [intuit/CardParts#148]
Hi,

When working with a single `CardPartTableView`, I would expect there to be a top margin of about 10.0 or so, but there is no margin. In the documentation it states that cards have a default margin all around them, but that doesn't seem to be true for the top margin of the first card in the view. As a result, this is what it looks like: 
![image](https://user-images.githubusercontent.com/39338264/61231558-5800e800-a6fa-11e9-9bb6-47bd1c36ea7e.png)

I've tried implementing the `NoTopBottomMarginsCardTrait` protocol on my `CardPartsViewController` subclass, and manually implementing the `requiresNoTopBottomMargins()` method to return `false`, but no change. I tried to manually create a `CardPartSpacerView(height: 30.0)` called `aboveSpacerPart` and included that in my array passed to `setupCardParts([])`, but that didn't make any difference either. I even tried to manually set the margins on the `CardPartTableView` to this: `tableViewPart.margins = UIEdgeInsets(top: 10.0, left: 14.0, bottom: 14.0, right: 10.0)`. For some reason, it doesn't seem like I can get there to be a margin on top of this `CardPartTableView`. Any reason why that might be so?

**Comment by croossin** [comment]
@hoidofyolen Can you attach a screenshot of the debug view hierarchy? Are you still facing this issue?

**Comment by hoidofyolen** [comment]
Yes, still seeing this issue. Is this what you mean by debug view hierarchy? It's the only place I know that has debug information without hitting a breakpoint.
![image](https://user-images.githubusercontent.com/39338264/62259273-c4a70280-b3db-11e9-865e-7657a6da03ae.png)

**Comment by hoidofyolen** [comment]
Nevermind, I found it. Here's what I think is the culprit constraint:

![image](https://user-images.githubusercontent.com/39338264/62259838-c1ad1180-b3dd-11e9-8a35-a8bbc8c63b2d.png)

**Comment by croossin** [comment]
Very interesting... let me take a look and get back to you!

**Comment by croossin** [comment]
@hoidofyolen If you clone this repo and run the example app and in `MainViewController.swift` comment out all of the cards except for the `CardPartTableViewCardController()` and run, do you still see the same issue? Maybe this is only happening for ViewControllers pushed on the navigation stack.

**Comment by badrinathvm** [comment]
@hoidofyolen i am looking in to this issue,  u can add a `CardPartSpaceView(height:10)` and then add the `CardPartTableView` in the navigationController. some thing like below 

`setupCardParts([CardPartSpaceView(height:10),CardPartTableView() ])`

**Comment by badrinathvm** [comment]
@hoidofyolen just did a sanity check , works as expected , see the below code and attached screenshot.
```
class TestViewController: CardPartsViewController {
    let cardPartTableView = CardPartTableView()
    let viewModel = CardPartTableViewModel()
    
    override func viewDidLoad() {
        
        self.view.backgroundColor = UIColor.gray
        cardPartTableView.margins.top = 120.0
        
        viewModel.listData.asObservable().bind(to: cardPartTableView.tableView.rx.items) { tableView, index, data in
            
            guard let cell = tableView.dequeueReusableCell(withIdentifier: "CellId", for: IndexPath(item: index, section: 0)) as? CardPartTableViewCell else { return UITableViewCell() }
            
            cell.leftTitleLabel.text = data
            
            return cell
            }.disposed(by: bag)
        
        setupCardParts([cardPartTableView])
    }
}
```
![Simulator Screen Shot - iPhone X - 2019-07-31 at 19 44 44](https://user-images.githubusercontent.com/1479179/62261998-0b8cfc00-b3cc-11e9-8dd3-5910df0d71f5.png)

**Comment by hoidofyolen** [comment]
When I implemented your line `cardPartTableView.margins.top = 120.0`, I got this:
![image](https://user-images.githubusercontent.com/39338264/62262598-44869a00-b3e7-11e9-8b80-81c69a0a5ec4.png)

I _am_ able to supplement the space in the top margin by using the spacer view. This is how I did it:

```
class SpacerViewController: CardsViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        loadCards(cards: [SpacerCardController()])
    }
    
}
```

```
class SpacerCardController: CardPartsViewController, NoTopBottomMarginsCardTrait, TransparentCardTrait {
    
    override func viewDidLoad() {
        
        super.viewDidLoad()
        
        setupCardParts([CardPartSpacerView(height: 8)])
        
    }
    
    func requiresNoTopBottomMargins() -> Bool {
        return true
    }
    
}
```

**Comment by badrinathvm** [comment]
@hoidofyolen is your solved ?

**Comment by hoidofyolen** [comment]
No, the problem is still there, but I was able to use the temporary solution of using a transparent spacer view. But this shouldn't be the long-term solution for the platform.

**Comment by croossin** [comment]
Of course not. However, we are not able to reproduce the issue.  We are seeing the top margin work appropriately.  Is there possibly other constraints you are setting?

**Comment by hoidofyolen** [comment]
I don't have any other constraints set, as you can see from my screenshots. I think a little more effort should be put into trying to reproduce this issue, since it happens consistently for me. Maybe it has to do with having the view controller wrapped in a navigation controller?

**Comment by croossin** [comment]
@hoidofyolen We will continue to look into this issue
