### ISSUE TITLE
Scroll load more cards

### ISSUE THREAD

**Issue by pongponglau** [intuit/CardParts#150]
May i ask how i can load more cards (i.e. infinite scrolling) with this great card library?

Many thanks

**Comment by croossin** [comment]
You may call `loadCards(cards:)` with a new array of cards.

**Comment by chrispykim** [comment]
@croossin `loadCards(card:)` removes all existing cards and loads the new array of cards right? That isn't quite what I picture when I think about infinite scrolling; is there a way to append cards to the existing set rather than refreshing the view with a new set of cards?
