### ISSUE TITLE
Navigation Bar not showing when card on screen used

### ISSUE THREAD

**Issue by xRose1** [intuit/CardParts#168]
Hi Everyone
I created a viewcontroller from storyboard and I added a navigation bar to it. I set it as a CardsViewController and then I load the card from CardPartsViewController. I get the navigation bar hidden. I am not sure the constraints or how to fix. The cards hide my navigation bar and I need it so the user can have a back button. Anyone know how this can be done or changed? It might be simple but I cant think of what to change.

**Comment by deepankar23** [comment]
Hey XRose1...  Are you pushing the CardsViewController from CardPartsViewController or presenting it modally? If you are pushing then you don't need to add any navigation bar & you will get the navigation from the CardPartsViewController. But if you are presenting it, then it makes sense.

**Comment by croossin** [comment]
Hi @xRose1 - can you verify that this is still an issue? If it is, feel free to re-open the issue.
