### ISSUE TITLE
Archiving App with Xcode 11 / iOS 13: hanging

### ISSUE THREAD

**Issue by phr85** [intuit/CardParts#171]
Hello
I'm using CardParts with my App (iOS 13 SDK).
I can run the App in the simulator but if I try to Archiving App with Xcode 11 GM 2, it stuck. See screenshot:

<img width="539" alt="Screenshot 2019-09-20 19 42 54" src="https://user-images.githubusercontent.com/1322091/65347382-2cf5b180-dbdf-11e9-9da1-f8b570b07185.png">

Xcode version: 11 GM 2
Swift Version: 5
CardParts version: 2.16.0
CocoaPods: 1.8 b2; I also try with 1.7.2

**Comment by croossin** [comment]
Very interesting.. we haven't built on Xcode 11 yet. I will try to do that over the weekend.

Is your app currently using CardParts in production? If so, we would love to feature it in the README! Feel free to let us know and we can add it

**Comment by phr85** [comment]
Helllo @croossin 
Thank you for your feedback.
Yes, I'm using it in production:
https://itunes.apple.com/us/app/kompendium/id373040910?ls=1&mt=8

At the moment only for the "Subscription" view.

Looking forward for your feedback.

Bests

Philippe

**Comment by phr85** [comment]
I downloaded the Xcode 11 today from Mac App Store:
It stuck also but this time it's FirebaseMessaging. So maybe the problem is not directly related too "CardParts" Framework. 

<img width="595" alt="Screenshot 2019-09-21 at 11 08 24" src="https://user-images.githubusercontent.com/1322091/65371091-615d8200-dc60-11e9-93da-0a00378f3e6e.png">
