### ISSUE TITLE
Enable issue and PR templates

### ISSUE THREAD

**Issue by croossin** [intuit/CardParts#179]
In order to make CardParts more community friendly, we should have issue and PR templates.

**Comment by sudeepta14** [comment]
I am taking this up

**Comment by sudeepta14** [comment]
Hey this is already completed. Please do close the issue.

**Comment by croossin** [comment]
@sudeepta14 We still need to add PR templates 😄

**Comment by sudeepta14** [comment]
Ok, I will add it. Please assign it to me

**Comment by croossin** [comment]
Released in [2.17.0](https://github.com/intuit/CardParts/releases/tag/2.17.0)
