### ISSUE TITLE
Create a CardPartMapView

### ISSUE THREAD

**Issue by croossin** [intuit/CardParts#183]
It would be nice to have a CardPart that contains a MapView.  This MapView should have bindable properties so that a user can bind a CLLocation, zoom, etc. making the map reactive.

**Comment by codethebeard** [comment]
I'd be very interested in trying this out.

**Comment by croossin** [comment]
We can absolutely assign it to you! Let me know if you’d like to take it on. @codethebeard

**Comment by codethebeard** [comment]
Yeah, I'd like to give it a shot. I use Mint just about every day so it's cool to have an opportunity to work on something like this. I've never worked in a framework before, so it's new territory for me but I have RxSwift/RxCocoa experience and a child-like sense of wonder.

**Comment by croossin** [comment]
That’s awesome to hear! I just assigned the ticket to you.  Please reach out if you have any questions.

**Comment by croossin** [comment]
Released in [2.17.0](https://github.com/intuit/CardParts/releases/tag/2.17.0)
