### ISSUE TITLE
Ambiguous reference when binding to the title of a button

### ISSUE THREAD

**Issue by dtumer** [intuit/CardParts#20]
It looks like that RxSwift has a function called "title()". When trying to bind to the title of a button through RxSwift there is an ambiguous reference build error in Xcode.

The fix should be easy we should just be able to rename the binder variable that is exposed in CardPartButtonView.swift so that it does not conflict with the RxSwift function

**Comment by croossin** [comment]
Maybe something like `buttonTitle`

**Comment by croossin** [comment]
This is complete via PR #21 .
