### ISSUE TITLE
Custom margins per CardController

### ISSUE THREAD

**Issue by jmjordan** [intuit/CardParts#207]
**Is your feature request related to a problem? Please describe.**
Yes, cards within a CardsViewController must all have the same margin.

**Describe the solution you'd like**
I'd like a way to specify a custom margin for an individual card with a CardsViewController. The main reason is to specify 0 margin for things like transparent cards that need to be the full width of the view.

**Describe alternatives you've considered**
Instead of allowing for any margin, the solution could just be for cards that need to be the full width of the screen.

**Additional context**
I have completed the feature on my fork and am ready to submit a PR if this idea is approved.

**Comment by croossin** [comment]
This is awesome, @jmjordan. Please open a PR so that we can take a look. Looking forward to reviewing it!

**Comment by badrinathvm** [comment]
@jmjordan this feature is already present make use of  below parameter to
set custom margins, by default they are set to default cardPart theme
margins.

// allow customization of cardCellMargins for an individual
CardsViewController; still default to theme
public var cardCellMargins : UIEdgeInsets = CardParts.theme.cardCellMargins


Thanks,
Badarinath

**Comment by jmjordan** [comment]
>This is awesome, @jmjordan. Please open a PR so that we can take a look. Looking forward to reviewing it!

@croossin Will do!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jmjordan** [comment]
>@jmjordan this feature is already present make use of  below parameter to ...

@badrinathvm I believe that feature only allows having a custom margin for all cards in a CardsViewController. My proposed feature would allow for custom margins on individual cards. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by badrinathvm** [comment]
Yes the parameter which I mentioned does for all the cards not for
individual ones. Would be available to see your PR and validate.

Thanks,
Badarinath

**Comment by croossin** [comment]
@badrinathvm As Jordan mentioned, we only have the ability to set for all cards, not individual cards. @jmjordan Please open a PR 😄 thanks.

**Comment by badrinathvm** [comment]
Yes @croossin , I mentioned Jordan to create a PR to validate.

**Comment by jmjordan** [comment]
PR: https://github.com/intuit/CardParts/pull/208

**Comment by croossin** [comment]
Completed in PR #208 and [Version 2.22.0](https://github.com/intuit/CardParts/releases/tag/2.22.0)
