### ISSUE TITLE
Could you show a sample on how to handle a menu Item popup

### ISSUE THREAD

**Issue by willysharp5** [intuit/CardParts#24]
This statement is confusing.

"The menuOptionObserver property can be set to a block that will be called when the user selects an item from the menu"

Thanks

**Comment by croossin** [comment]
Hi! Sure, sorry for the confusion.  Here is how you would set the `menuOptionObserver` property:

```swift
let titlePart = CardPartTitleView(type: .titleWithMenu)
titlePart.menuTitle = "Hide this offer"
titlePart.menuOptions = ["Hide"]
titlePart.menuOptionObserver  = {[weak self] (title, index) in
    // Logic to determine which menu option was clicked
    // and how to respond
    if index == 0 {
        self?.hideOfferClicked()
    }
}
```

You can now see this reflected in the [CardPartTitleView Documentation](https://github.com/intuit/CardParts#cardparttitleview).
