### ISSUE TITLE
Cannot find type 'CardsViewController' in scope

### ISSUE THREAD

**Issue by Ehsan-Home** [intuit/CardParts#267]
Hello everyone. First of all, thank you for your amazing library. Super useful so far 🚀

I have a problem loading this library into my Xcode project. 

This is my podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Test-Cocopod' do
    pod 'CardParts'
end
```

After running pod install, I get the following result in my terminal:

![Screen Shot 2020-11-14 at 9 11 27 PM](https://user-images.githubusercontent.com/32008442/99171447-fd94e480-26bd-11eb-93aa-e3b2429e8747.png)

Finally, I add the following code to my ViewController:

![Screen Shot 2020-11-14 at 9 12 21 PM](https://user-images.githubusercontent.com/32008442/99171458-1b624980-26be-11eb-9cf4-9778577082ca.png)

However, I get the following error:

![Screen Shot 2020-11-14 at 9 13 07 PM](https://user-images.githubusercontent.com/32008442/99171472-359c2780-26be-11eb-915c-b8f3c9176c2a.png)

How can I solve this issue? 

Sorry if my question is kind of obvious since I'm just the beginner at Swift.

Appreciated 😃

**Comment by bharathmurs** [comment]
Hi @Ehsan-Home, 
I see you are missing `import CardParts`. That shall help you fix the issue.

**Comment by Ehsan-Home** [comment]
Got you.

Thank you.
