### ISSUE TITLE
Override CardParts to add custom Views 

### ISSUE THREAD

**Issue by willysharp5** [intuit/CardParts#29]
I would like to add a Charting View to the CardParts. Kinda like you have with Intuit's Charts. 
Is there a way to do that? 

In general is there a way to adding a custom view

Thanks

**Comment by dtumer** [comment]
Hi! Yes you definitely can! We have not included any documentation on it at the moment but we will be  releasing that documentation soon.

What you can do is very similar to what we have done with `CardPartBarView`. What you would need to do is create a card part that extends a UIView and then implements the `CardPartView` interface. The required variable to implement would be `margins`. Basically you need to return the margins of the object. This value can be retrieved using `CardParts.theme.cardPartMargins`. This value will return the margins of whatever theme your card parts is setup to use (You may also make custom margins although this may not be compatible with any out of the box themes provided).

From there everything is up to you! Use your creativity to create the view any way you would like. You will need to create the UIView for your Charting View programmatically inside of the initializer for the card part.

Finally, you may also include any reactive binders to your Charting View that you would like to expose to the outside world. These binders will allow other developers to detect changes in the data of your card part and update it accordingly. An example of what you are looking for is included below:

```swift
public class CardPartChartView: UIView, CardPartView {
   public var margins: UIEdgeInsets = CardParts.theme.cardPartMargins

   public init() {
      super.init(frame: CGRect.zero)

      // your UIView creation code goes here
   }
}

extension CardPartChartView {
   // some variable you would like to allow developers to data bind to
   public var someChartValue: Binder<CGFloat> {
      return Binder(self.base) { (chartView, someChartValue) in
         chartView.someChartValue = someChartValue
      }
   }
}
```

I hope that this is helpful and gives you a good start in designing your very own card parts! I am excited to see a PR from you soon 😄

**Comment by willysharp5** [comment]
Great. Thanks
