### ISSUE TITLE
Ability to add custom CardStates

### ISSUE THREAD

**Issue by croossin** [intuit/CardParts#36]
We should allow users to be able to make custom CardStates so they can setup their CardParts for as many states as they would need.

**Comment by croossin** [comment]
@lwdupont https://github.com/intuit/CardParts#card-states

**Comment by lwdupont** [comment]
What kind of other states do people want? Why would I want to add a custom state via card parts, vs just adding some other var on my subclass?

Not judging. Just curious. 😄

**Comment by croossin** [comment]
So currently we give developers the option to choose from one of the following states:
```swift
public enum CardState {
	case none
	case loading
	case empty
	case hasData
}
```
What if none of those states made sense for the developer? They may want to have a card in the `.signedUp` or `.loggedIn` state to show something different.  Or, they have more than 4 possible states the card could be in. In my opinion, the framework should not care about how many states there are or what they are named, but instead just know which parts belong to which state and when those states change, show the matching parts.

What are your thoughts on that? Do you agree? I just have had cases where I'll put a card in a certain state like `.empty` and then have some comment that says `// this is when the user is in xyz state`.

**Comment by bharathmurs** [comment]
I would say having strings would give user flexibility to define their own states. Having enums would be limited. 

```
struct CardState {
    static let none = "none"
    static let empty = "empty"
    static let loggedIn = "loggedIn"
    static let loggedOut = "loggedOut"
}
```

`setupCardParts([titlePart, textPart], forState: CardState.loggedIn)`
`setupCardParts([titlePart, textPart], forState: CardState.loggedOut)`

**Comment by dtumer** [comment]
I actually have a perfect use case for this right now. Is this going to be done anytime soon or should I work on this?

I have a use case where I have a .loading version of one of my cards, but depending on data that is binded on the card I need the card layout to change. There's not enough states for me to be able to include all of the changes. I'd need to be able to define my own states as well

**Comment by lwdupont** [comment]
Makes total sense btw.. sorry been out sick the past few days.. you all are cranking on this!
