### ISSUE TITLE
Example loads empty UI

### ISSUE THREAD

**Issue by efremidze** [intuit/CardParts#4]
The example project toggles between 2 empty cards. I doubt this is the desired behavior.

![simulator screen shot - iphone x - 2018-05-20 at 11 40 05](https://user-images.githubusercontent.com/2286277/40282324-8d3e39ce-5c22-11e8-9248-a7f2fada7144.png)
![simulator screen shot - iphone x - 2018-05-20 at 11 40 07](https://user-images.githubusercontent.com/2286277/40282325-8ea19c5c-5c22-11e8-9ffb-2187a2963792.png)

**Comment by croossin** [comment]
This is more showing that the cards have the ability to auto-resize based on the CardParts that are in them :) Feel free to look into the Cards that are being loaded in the example and you can alter which CardParts that compose them.
