### ISSUE TITLE
get superview of a card parts

### ISSUE THREAD

**Issue by pprevalon** [intuit/CardParts#67]
how can i get the superview of part in a card for example i have an image part i want to do imagePart.superview

**Comment by bharathmurs** [comment]
@pprevalon  When are you trying to access `superview`? You should definitely be able to access `imagePart.superView` after `viewDidLoad` is complete, say in some call back or something. 
However superView would be nil if you are trying to access while creating the cardParts in viewDidLoad. 

What is the particular use case you are seeing the issue with?

**Comment by pprevalon** [comment]
I did set it in in view didLoad but the parentView still came back nil, I have an imageview but i do not want to set the width i want it to constraint to left and right of the parent view.

**Comment by bharathmurs** [comment]
@pprevalon Yeah in viewDidLoad if you try to access `parentView` it will comeback as `nil`. 
You don't have to set width constraint. All cardparts do have their constraints set to its parent view. 
Make use of `margins` on cardPart to define your constraints.

Ex: To set left and right constraints just try setting `imagePart.margins.left` and `imagePart.margins.right`.

**Comment by pprevalon** [comment]
nice that worked out well by using margins thank you.

**Comment by bharathmurs** [comment]
Glad that it worked. 👍 
So, closing the issue.
