### ISSUE TITLE
Why cards left and right margin missing?

### ISSUE THREAD

**Issue by Jinkeycode** [intuit/CardParts#69]
In your demo，I run it finding that the card has left and right margin, just like this:

![](https://raw.githubusercontent.com/Intuit/CardParts/master/images/mintCardParts.gif)

But the same code I copied to my project，the  left and right margin was missing, just like this:

![](https://raw.githubusercontent.com/Intuit/CardParts/master/images/turboCardParts.gif)

How should I code to has margin？

**Comment by croossin** [comment]
Which CardPart are you using to try to mimic that behavior?

**Comment by croossin** [comment]
@Jinkeycode Which CardPart are you using for this? These were [CardPartTitleDescriptionView](https://github.com/intuit/CardParts/blob/master/CardParts/src/Classes/Card%20Parts/CardPartTitleDescriptionView.swift).  Now looking at our docs, it seems we skipped over that on accident!  See issue #70 for details.  We will have documentation by EOD!

**Comment by croossin** [comment]
@Jinkeycode The [documentation](https://github.com/intuit/CardParts#cardparttitledescriptionview) as well as working code [example](https://github.com/intuit/CardParts/blob/master/Example/CardParts/CardPartTitleDescriptionViewCardController.swift) is now merged into master. Feel free to take a look and reopen if you have more questions!

**Comment by bharathmurs** [comment]
@Jinkeycode If you mean by cell margins, then try setting cardCellMargins under CardPartsTheme.

```
public class YourCardPartTheme: CardPartsTheme {
    public var cardCellMargins: UIEdgeInsets = UIEdgeInsets(top: 10.0, left: 15.0, bottom: 10.0, right: 15.0)
}
```
and
`YourCardPartTheme().apply()`

This should give you left and right margins of 15 pts for the card.

Hope this helps.

**Comment by baryon** [comment]
How can get this example code like your screen gif?
