### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by croossin** [intuit/CardParts#7]
We should have a more in-depth example app that shows all of the different style CardParts and some of the available traits.

**Comment by lwdupont** [comment]
Ya, I'm in to do some :)

**Comment by lwdupont** [comment]
What do you think about making the first view a set of cards that list different examples? Or categories of examples? Or a tab bar with some different major types?

**Comment by croossin** [comment]
Yes, I really like that idea.  @lwdupont did you want to take that up? Or we can create a side branch and work on it together? Up to you.

**Comment by lwdupont** [comment]
I'll make a side branch, and you can answer my questions? :) (and help if I'm too slow) :)

**Comment by croossin** [comment]
Completed with #13
