### ISSUE TITLE
How to easily remove the card ?

### ISSUE THREAD

**Issue by Jinkeycode** [intuit/CardParts#72]
When I write the delete event in CardPartsViewController, how can I easily remove the specified card ( actually CollectionViewCell ) in CardsViewController ?

**Comment by croossin** [comment]
What do you mean by the delete event in `CardPartsViewController`? If you want to remove a card, you can use [CardStates](https://github.com/intuit/CardParts#card-states) to chose which cards are showed given the current state.

**Comment by Jinkeycode** [comment]
Just Like the slide left to delete or edit in tableview

**Comment by croossin** [comment]
There is no "swipe" per se.  You can have a CardPartTableView and allow the cells to swipe but each CardPart has no "swipe" functionality.  If that didn't answer the question, feel free to open again!
