### ISSUE TITLE
how can i update from async

### ISSUE THREAD

**Issue by pprevalon** [intuit/CardParts#73]
I want to decide what card depending on what result i get from an async result but when i attempt to change nothing happing here is my current async code

GMSPlacesClient().lookUpPhotos(forPlaceID: place!.placeID) { (dataList, error) in
            if error != nil {
                print(error!)
                return
            }
            if let result = dataList?.results {
                if result.count > 0 {
                    GMSPlacesClient().loadPlacePhoto((dataList?.results[0])!, callback: { (image, error) in
                        if error != nil {
                            print(error!)
                            return
                        }
                        DispatchQueue.main.async {
                            
                            let card = imgCard()
                            card.cardPartImage.image = image
//                            self.cardViewController.loadCards(cards: [card,cardBottom])
                            self.cardViewController.reload(cards: [card,cardBottom])

                            constrain(self.cardViewController.view) { (tv) in
                                tv.height == self.view.frame.size.height
                                tv.leftMargin == tv.superview!.leftMargin + 6
                                tv.rightMargin == tv.superview!.rightMargin - 6
                            }
                            
                            constrain(self.cardViewController.view) { (tv) in
                                tv.height == self.cardViewController.collectionView.contentSize.height
                                tv.bottom == tv.superview!.bottom
                            }
                        }
                    })
                } else {
                    DispatchQueue.main.async {
                        let card = NoImgCard()
                        self.cardViewController.reload(cards: [card,cardBottom])
//                        self.cardViewController.loadCards(cards: )
                    
                        constrain(self.cardViewController.view) { (tv) in
                            tv.height == self.view.frame.size.height
                            tv.leftMargin == tv.superview!.leftMargin + 6
                            tv.rightMargin == tv.superview!.rightMargin - 6
                        }
                        constrain(self.cardViewController.view) { (tv) in
                            tv.height == self.cardViewController.collectionView.contentSize.height
                            tv.bottom == tv.superview!.bottom
                        
                        }
                    }
                }
            } else {
            }
        }

**Comment by croossin** [comment]
@pprevalon Hi! Thanks for checking out CardParts. Do you mind formatting your comment so that the all of the code is in a codeblock? It will make it easier for us to help you!

**Comment by croossin** [comment]
@pprevalon I will close this issue... but feel free to reopen if you need help still!
