### ISSUE TITLE
Add an method to modify distribution

### ISSUE THREAD

**Issue by Helen-Xu** [intuit/CardParts#76]
The current distribution mode is set to equalSpacing, which is nice for some cards. However, it's preventing me from placing a cardPart at a certain position. Is it possible to add an function like modifyDistribution to switch distribution to .fill, so that cardParts will be placed according to margins?

**Comment by lwdupont** [comment]
@croossin I asked Helen to post this, she's working on our Turbo team right now. :)

**Comment by bharathmurs** [comment]
@PenguinRAD What does it mean by placed according to margins? 
Current setupCardParts does place the cardParts as per the margins. Can you give an example with an image?

**Comment by bharathmurs** [comment]
After talking to @PenguinRAD, we will take a look at the implementation of `CardPartCollectionViewCardPartsCell` so that the spacing b/w the elements adhere to the margins set.

**Comment by lwdupont** [comment]
Feel free to ask her to do it too :)

**Comment by croossin** [comment]
@bharathmurs @Helen-Xu Was this completed by #77 ?

**Comment by lwdupont** [comment]
Yup.

**Comment by croossin** [comment]
Closing since completed by #77
