### ISSUE TITLE
cardCellMargins.top don't works

### ISSUE THREAD

**Issue by baryon** [intuit/CardParts#84]
I set cardCellMargins top to want add space, but it don't works
```
        let theme = CardPartsMintTheme()
        theme.cardCellMargins = UIEdgeInsets(top: 200.0, left: 150.0, bottom: 100.0, right: 15.0)
        theme.apply()

```
![simulator_screen_shot_-_iphone_7_-_2018-08-28_at_11_03_22](https://user-images.githubusercontent.com/421757/44696375-4e569d80-aab2-11e8-91d3-850702c150c0.png)

**Comment by bharathmurs** [comment]
@baryon Firstly sorry for the delayed response. 

`cardCellMargins`'s top and bottom was intended for top and bottom margins within the cell. 
However, for your question on "How add space?", you can achieve that by setting contentInset on the collectionView on your `CardsViewController`.

Like say,
`self.collectionView.contentInset.top = 50.0`

**Comment by baryon** [comment]
thanks
