### ISSUE TITLE
Trouble running the example project

### ISSUE THREAD

**Issue by kdsaft** [intuit/CardParts#91]
I'm having trouble building the example project.

I cloned the repo, installed the pod from within the Example directory, switched the signing, opened from the workspace....all good. When I go to build, however, I get this issues:

`'_lock' is inaccessible due to 'private' protection level
`
in **RxSwift/extension DisposeBag**

I tried to update the project to 4.2, but that caused additional issues. And I also tried switching the build language version to swift 4.0 (rather than 3.0). No joy.

Any thoughts on what I'm doing wrong?

Thanks! Keith

**Comment by bharathmurs** [comment]
@kdsaft It might seem like your RxSwift target might be building on swift 3. Can you double check and make it build against swift 4 and try?

**Comment by kdsaft** [comment]
@bharathmurs: you're a genius! Thank-you. :-)

**Comment by croossin** [comment]
Thanks @bharathmurs for helping out @kdsaft.  Let us know if you have any more questions, @kdsaft  👍
